#!/bin/bash

echo "You need to re-authenticate with gcloud."
echo "Please run the following commands manually:"
echo ""
echo "1. Re-authenticate:"
echo "   gcloud auth login"
echo ""
echo "2. After authentication, run the deletion script:"
echo "   cd /Users/bogdanionutcoman/dev-projects/RentalSpot-Builder"
echo "   ./scripts/delete-revisions-simple.sh"
echo ""
echo "Alternatively, use the Cloud Console UI:"
echo "https://console.cloud.google.com/run/detail/europe-west4/prop-management/revisions?project=rentalspot-fzwom"
echo ""
echo "In the Cloud Console:"
echo "1. Go to the Revisions tab"
echo "2. Select all revisions except the one currently receiving traffic"
echo "3. Click 'Delete' button"